### PR TITLE
Fixes for Django 1.9

### PR DESCRIPTION
**Pull request by andy128k**

### CODE REVIEW

**Comment by jonasvp** [comment]
Thanks for the PR! Unfortunately, we need to support older Django versions as well, so we'd need to use something like https://github.com/wq/django-swappable-models/pull/9/files

**Comment by andy128k** [comment]
@jonasvp Do you have to support Django 1.6 or earlier?

**Comment by jonasvp** [comment]
Good question. @anrie?

**Comment by anrie** [comment]
Though we dropped explicit tests for older versions I think the current release (1.0.2) should run on newer versions than Django 1.4.

Regarding Django 1.9 you should also consider this discussion: https://github.com/jonasundderwolf/django-image-cropping/issues/80
On my machine the selenium test are currently a bit shaky and I didn't have time to look into it so I can't tell for sure if there are still issues to be resolved.

**Comment by anrie** [comment]
I just published a new version that incorporates the necessary fixes for 1.9:
https://pypi.python.org/pypi/django-image-cropping/1.0.3

**Pull request closed without merging**
