### PR TITLE
fix: add request to formfield_for_dbfield signature (#134)

### PR DESCRIPTION
**Pull request by bmihelac**

### CODE REVIEW

**Comment by bmihelac** [comment]
I see, that django-image-cropping supports older Django. I'll update to accomodate this ASAP

**Comment by nortigo** [comment]
Any updates?

**Comment by MRigal** [comment]
@bmihelac you're right, the signature is not up-to-date. Would you like to rebase on the actual master, also to incorporate the latest super() call?

**Comment by bmihelac** [comment]
@MRigal sure, would do it as soon as I catch some time

**Comment by bmihelac** [comment]
This has been rebased to master, please let me know if anything else is needed.

**Comment by MRigal** [comment]
Thanks @bmihelac for the contribution! I'll wait on feedback on https://github.com/jonasundderwolf/django-image-cropping/issues/140 to merge #148 and release a new version! :-)

**Comment by bmihelac** [comment]
@MRigal thanks for quick action :)

**Pull request merged**
