### PR TITLE
Django 3.0 compatibility

### LINKED ISSUE #136: Django 3.0 compatibility
Error occured:

> ImportError: cannot import name 'admin_static'

https://docs.djangoproject.com/en/dev/releases/3.0/

> The staticfiles and admin_static template tag libraries are removed.

### PR DESCRIPTION
**Pull request by Mogost**
Fix #136 
- Drop support for Python < 3.5
- Drop support for Django < 2.2
- Add Support for Django 2.2, 3.0

### CODE REVIEW

**Comment by Mogost** [comment]
Tests for Django 3.0 are failed due to new version of easy-thumbail is not released yet

**Comment by Mogost** [comment]
@anrie 
I think that this PR is ready for merge and release.

**Comment by anrie** [comment]
@Mogost Thank you! This looks really good from a quick glance.

I take a closer look in the coming days and see that I issue a new release.

**Comment by anrie** [comment]
Very nice, thank you  @Mogost!

**Pull request merged**
